- Sources/SwiftKafka/KafkaPartition.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/KafkaProducerMessage.swift
- Sources/SwiftKafka/KafkaTopicConfig.swift
- Tests/SwiftKafkaTests/KafkaTopicConfigTests.swift
To be able to send messages to Kafka we need auxiliary types such as
* `KafkaProducerMessage`
* `KafkaTopicConfig`
* implemented `KafkaProducerMessage`
* created implementation for `KafkaTopicConfig` that matches
`KafkaConfig`s copy-on-write mechanism and has tests
* created barebones of `KafkaProducer` class
> Auxiliary types for sending Messages to Kafka

- Sources/SwiftKafka/KafkaProducer.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
Parameter label not necessary for single argument function whose parameter type is well known.
`KafkaProducer.sendAsync(message:)` -> `KafkaProducer.sendAsync(_:)`
> Removed parameter label for KafkaProducer.sendAsync

- Package.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
This PR closes #23.
* changed `swift-nio` dependency from `branch: main` to `from: 2.43.1`
* updated code to conform to new `NIOAsyncSequenceProducer` interface
> Update `swift-nio` dependency

- Sources/SwiftKafka/KafkaAcknowledgedMessage.swift
- Sources/SwiftKafka/KafkaAcknowledgedMessageError.swift
- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConfig.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaConsumerMessage.swift
- Sources/SwiftKafka/KafkaError.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/KafkaTopicConfig.swift
- Tests/IntegrationTests/Utilities.swift
Closes issues:
#25, #29 
The general idea is to have a **single error type (namely `KafkaError`)** that is used for all errors in the program. 
However, I still kept the `KafkaAcknowledgedMessageError` as we somehow need to provide our users with a convenient way to access the `messageID` of a failed message acknowledgement.
The challenge I faced in this PR is that the C library comes with its error types that shall not be exposed publicly. My solution is to wrap the C library's errors inside a dedicated `case` of the `KafkaError` type.
> Improved implementation of `KafkaError` and `KafkaAcknowledgedMessageError`

- CODE_OF_CONDUCT.md
We're centralizing on the Swift code of conduct, so we'll x-reference that instead of holding our own.
Hyperlink out to Swift.
Shared CoC across the projects.
> Adopt the Swift Coc

- Sources/SwiftKafka/Configuration/KafkaConsumerConfig.swift
- Sources/SwiftKafka/Configuration/KafkaProducerConfig.swift
* the `allow.auto.create.topics` was missing in our `KafkaProducerConfig`
> **Note**: the default value for `allow.auto.create.topics` is `true` for `KafkaProducerConfig` and `false` for `KafkaConsumerConfig` (this is adapted from `librdkafka`)
* add `allow.auto.create.topics` option to `KafkaProducerConfig`
> KafkaProducerConfig: add `allow.auto.create.topics` option

- Package.swift
- README.md
- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafka.swift
- Sources/SwiftKafka/RDKafka/RDKafkaConfig.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
* fix typo in `SwiftKafkaTests`
* upgrade minimum OS versions to support the `Duration` type
* move conversion of `rd_kafka_message_t` to `KafkaAcknowledgementResult` to `RDKafkaConfig` so that we can pass the `KafkaAcknowledgementResult` type as early as possible and don't have to bother with `UnsafePointer<rd_kafka_message_t>` in all our delivery callback logic
* expose KafkaProducer.run() method
* `README`: use `TaskGroup` in `KafkaProducer` example
* add comments to task groups in `README`
* refactor all tests into using task groups (structured concurrency)
We want to have a `KafkaProducer` that is not consuming any acknowledgements. This means it is initialized without a `deliveryReportCallback` which in turn means that `librdkafka` will not queue any incoming acknowledgements which …
> KafkaProducer: Expose `run()` method

- Sources/SwiftKafka/KafkaAcknowledgedMessage.swift
- Sources/SwiftKafka/KafkaAcknowledgedMessageError.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/KafkaProducerMessageID.swift
- Sources/SwiftKafka/RDKafka/RDKafkaConfig.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
> **Warning**: this can potentially be a breaking change as message ids
> will lose their chronological order in the public API after this
> change.
We don't want to expose `UInt` for `KafkaProducer`'s message ids.
* create a new `struct` `KafkaProducerMessageID` that is internally
backed by `UInt` (can also be `UUID` or similar in the future)
* update tests
> Dedicated `KafkaProducerMessageID` type

- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/RDKafka/RDKafkaConfig.swift
> **Info**: this PR sits of top of #68
[rd_kakfa_consumer_close](https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafka_8h.html#a37b54d329e12d745889defe96e7d043d)
was blocking. This PR proposes using the
[rd_kakfa_consumer_close_queue](https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafka_8h.html#a9dd5c18bdfed81c8847b259f0a8d498d)
API which is non-blocking and served through the normal poll loop.
* `KafkaClient.consumerClose`: use `rd_kakfa_consumer_close_queue` in
favour of `rd_kakfa_consumer_close`
* create a new variable `KafkaClient.isConsumerClosed` that indicates
if the poll loop needs to continue polling or if it can stop running
* updated state management in `KafkaConsumer` to accomodate for polling
when the `KafkaConsumer` is in the …
> Fix: `KafkaClient.closeConsumer` should not block

- README.md
- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafkaTopicHandles.swift
- Sources/SwiftKafka/Utilities/NIOAsyncSequenceProducerBackPressureStrategies+NoBackPressure.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
> **Fixes**: #64 
* align `KafkaProducer` more with proposed changes to `KafkaConsumer`
* `AsyncStream` was not handling `AsyncSequence` termination handling as
we wanted it to, so revert back to use `NIOAsyncSequenceProducer`
* make `KafkaProducer` `final class` instead of `actor`
* `KafkaProducer`: use `NIOAsyncSequenceProducer` instead of
`AsyncSequence` for better termination handling -> shutdown
`KafkaProducer` on termination of the `AsyncSequence`
* introduce `StateMachine` to `KafkaProducer`
* move the internal state of `KafkaProducer` to `KafkaProducer.StateMachine`
* remove unused `await` expressions when accessing `KafkaProducer`
* update tests
* update `README`
> Refactor `KafkaProducer`

- Package.swift
- README.md
- Sources/SwiftKafka/Configuration/KafkaConsumerConfiguration.swift
- Sources/SwiftKafka/Configuration/KafkaProducerConfiguration.swift
- Sources/SwiftKafka/Configuration/KafkaTopicConfiguration.swift
- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaConsumerMessage.swift
- Sources/SwiftKafka/KafkaPartition.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafkaConfig.swift
- Sources/SwiftKafka/RDKafka/RDKafkaTopicHandles.swift
- Sources/SwiftKafka/Utilities/NIOAsyncSequenceProducer+Helpers.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
> Closes #57 
* add `swift-service-lifecycle` aka `ServicLifecycle` dependency to
`Package.swift`
* add `Sendable` conformance to the following types:
* `KafkaProducerConfiguration`
* `KafkaConsumerConfiguration`
* `KafkaTopicConfiguration`
* `KafkaPartition`
* `KafkaClient`
* `KafkaConsumerMessages`
* `KafkaConsumerMessage`
* `RDKafkaConfig.CapturedClosures`
* `RDKafkaTopicHandles`
* add `@unchecked Sendable` conformance to the following types:
* `KafkaProducer`
* `KafkaConsumer`
* add `Service` conformance to the following types:
* `KafkaProducer`
* `KafkaConsumer`
* `SwiftKafkaTests`:
* use `ServiceGroup`s
* `KafkaProducerTests`:
* use `ServiceGroup`s
* remove `testFlushQueuedProducerMessages` as it relied on the now
`private` implementation detail `triggerGracefulShutdown`
* remove …
> Adopt `swift-service-lifecycle`

- Package.swift
- Sources/SwiftKafka/KafkaAcknowledgedMessage.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/KafkaProducerMessageID.swift
https://github.com/apple/swift-nio/pull/2459 has been merged.
* `Package.swift`: upgrade `swift-nio` to `2.55.0`
* make `KafkaAcknowledgedMessage` `Sendable`
* make `KafkaProducerMessageID` `Sendable`
* remove `@unchecked Sendable` in `KafkaProducer.StateMachine.State`
* remove `@unchecked Sendable` in `KafkaConsumer.StateMachine.State`
> Remove `@unchecked Sendable`

- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafka.swift
- Sources/SwiftKafka/RDKafka/RDKafkaConfig.swift
- Sources/SwiftKafka/RDKafka/RDKafkaEvent.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
Currently we serve `librdkafka` logs and delivery reports through
callbacks. In the future we also want to get notified about `librdkafka`
triggered errors, statistics and rebalances. As having the callbacks
adds a lot of overhead e.g. by having `Unmanaged` references and having
to wrap Swift closures in C callbacks, we rather want to have an
`eventPoll` method that regularly polls for all sorts of events and
handles them inline.
* `KafkaClient`
* remove `poll` method
* add new method `eventPoll`
* move mapping from `librdkafka` logs to `swift-log` to
`KafkaClient.eventPoll`
* `KafkaProducer`:
* receive acknowledgements through `KafkaClient.eventPoll` instead of using
`KafkaClient.poll` to trigger event callbacks
* replace `deliveryReport` callback and handle deliveryReport event directly …
> `KafkaProducer`: replace callbacks with `eventPoll`

- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/Utilities/NIOAsyncSequenceBackPressureStrategies+NoBackPressure.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
- Tests/SwiftKafkaTests/KafkaProducerTests.swift
We do not to buffer any incoming messages when the asynchronous
sequences we expose are terminated.
This PR proposes adding a new state to `KafkaProducer` that drops any incoming acknowledgements after the asynchronous
sequence has been terminated.
> **Note**: we are not shutting down entirely as terminating the `run()`
loop early is seen as an error is `swift-service-lifecycle`.
* add new `NIOAsyncSequenceProducerDelegate` `KafkaProducerCloseOnTerminate`
* `KafkaProducer`: add new stateMachine logic
`stopConsuming` that does not stop the poll loop but drops all
incoming messages / acknowledgements
* add test
`KafkaProducerTests.testSendFailsAfterTerminatingAcknowledgementSequence`
> `KafkaProducer`: Drop acks on sequence termination

- README.md
- Sources/SwiftKafka/Configuration/KafkaConsumerConfiguration.swift
- Sources/SwiftKafka/KafkaClient.swift
- Sources/SwiftKafka/KafkaConsumer.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafka.swift
- Tests/IntegrationTests/SwiftKafkaTests.swift
We want to avoid running out of memory when the user stops reading the
`KafkaConsumer.messages` `AsyncSequence`. Therefore we drop any incoming
messages that we receive after the `AsyncSequence` was terminated.
* `KafkaConsumer`
* enter idle polling state when `KafkaConsumer.messages`
`AsyncSequence` was terminated to ensure that the `func run()`
async does not return early and result in an error for its `ServiceGroup`
* `KafkaConsumerConfiguration`:
* proxy `enable.auto.commit` and make it `false` by default
Reason: our library should be in charge of deciding when a message
offset is to be commited because only we know if our library user received the message through the
`KafkaConsumer.messages` `AsyncSequence`
* `KafkaSharedConfiguration.partition`: document default value of
parameter …
> `KafkaConsumer`: drop messages on sequence termination

- Sources/SwiftKafka/Configuration/KafkaConfiguration+Security.swift
- Sources/SwiftKafka/Configuration/KafkaConfiguration.swift
- Sources/SwiftKafka/Configuration/KafkaConsumerConfiguration.swift
- Sources/SwiftKafka/Configuration/KafkaProducerConfiguration.swift
- Tests/SwiftKafkaTests/KafkaConsumerTests.swift
> **Note**: this PR sits on top of #87.
> Adds some of the missing properties from #46.
We were lacking some of the security protocol configuration options and
want to provide them in a type-safe manner.
* add Kerberos support
* add OAuthBearer support
* Created a new file `KafkaConfiguration+Security.swift`
* add `public struct` `SSLConfiguration`
* add `public struct` `SASLMechanism`
* add `public struct` `KerberosConfiguration`
* add `public struct` `OAuthBearerMethod`
* add `public struct` `SecurityProtocol`
* integrate `KafkaConfiguration.SSLOptions` in new types
* integrate `KafkaConfiguration.SASLOptions` in new types
```swift
var config = KafkaConsumerConfiguration(
consumptionStrategy: .partition(.unassigned, topic: "some topic")
)
config.securityProtocol = .saslSSL( …
```
> Type-safe Security Configuration

- Sources/SwiftKafka/Configuration/KafkaProducerConfiguration.swift
- Sources/SwiftKafka/KafkaProducer.swift
- Sources/SwiftKafka/RDKafka/RDKafkaClient.swift
With our own flushing implementation we were flushing until `rd_kakfa_outq_len`
reached `0`. However `rd_kakfa_outq_len` also takes other events such
as statistics into account which led to a race where we were flushing
for a very long time because more and more other events were produced to
the queue while we were flushing.
* `KafkaClient`:
* remove `var outgoingQueueSize`
* add new method `flush(timeoutMilliseconds:)` that executes the
blocking `rd_kafka_flush` call on a `DispatchQueue` but vends this
as an `async func`
* `KafkaProducer`:
* rename `KafkaProducer.StateMachine.State.flushing` to
`KafkaProducer.StateMachine.State.finishing`
* invoke `KafkaClient.flush` before terminating poll loop
> `KafkaProducer`: refactor flushing

- Sources/SwiftKafka/KafkaConsumer.swift
Closes #99.
* `KafkaConsumer`: only subscribe to `RDKafkaEvent.offsetCommit` when
`KakfaCOnsumerConfiguration.enableAutoCommit == false`
> Fix: `KafkaConsumer` crashes with autoCommit=true

- Sources/SwiftKafka/KafkaError.swift
- Sources/SwiftKafka/RDKafka/RDKafkaTopicConfig.swift
Error type was unused and should not clutter public API.
* remove `KafkaError.ErrorCode.acknowledgement` and all related code
* minor fix: throw `KafkaError.topicConfig` instead of
`KafkaError.config` in `KakfaTopicConfiguration`
> Remove `KafkaError.ErrorCode.acknowledgement`

- Sources/SwiftKafka/Data/String+KafkaContiguousBytes.swift
`String.count` is the character count, but not the byte count
* `String+KafkaContiguousBytes`: use `String.utf8.count` when creating
`UnsafeRawBufferPointer`
> Fix conversion from String to Bytes

- Package.swift
- Sources/KafkaFoundationCompat/Data+KafkaContiguousBytes.swift
Users should be able to use `Data` as key/value of `KakfaProducerMessage`.
* add new `.library` `"KafkaFoundationCompat"` alongside a new target
* make `Foundation.Data` conform to `KafkaContiguousBytes`
> `KafkaFoundationCompat`

- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/RDKafka/RDKafkaClient.swift
This PR fixes issue #110.
`KakfaConsumer`: by polling the `rd_kafka_queue_get_main` queue instead of the `rd_kafka_queue_get_consumer` queue,
the timer for `max.poll.interval.ms` did not get reset which eventually
resulted in a timeout despite polling. (See [`librdkafka`
documentation](https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafka_8h.html#acacdb55ae7cb6abfbde89621e512b078))
* `RDKafkaClient`:
* rename `mainQueue` to `queue`
* use `rd_kafka_queue_get_consumer` instead of
`rd_kafka_queue_get_main` for `KakfaConsumer` clients
-> this will reset the timer for `max.poll.interval.ms` so that
the consumer does not time out despite polling
* invoke `rd_kafka_queue_destroy(self.queue)` on
`RDKafkaClient.deinit` to loose reference to queue
> Fix: Kafka consumer leaves group after 5 mins

- Sources/Kafka/KafkaError.swift
* make `KafkaError` `@unchecked Sendable` (can be marked as `@unchecked
Sendable` because we use a backing class for storage aka copy-on-write)
> Fix sendability warnings

- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/KafkaProducer.swift
`KafkaProducer.makeeProducerWithEvents()`: initializing the
`NIOAsyncSequenceProducer` before the `client`and the `client` init throwing an erorr led to `KafkaProducerCloseOnTerminate` getting triggered in an invalid state which in turn resulted in a `fatalError`
* make designated initializer of `KafkaProducer` non-throwing
* `KafkaProducer.makeProducerWithEvents`:
* initialize `client` before
calling `NIOAsyncSequenceProducer.makeSequence`
-> if initializing `client` fails the appropiate error gets thrown
instead of triggering a fatalError because
`KafkaProducerCloseOnTerminate` gets triggered in an invalid state
When the initialization `KafkaProducer.makeProducerWithEvents` fails an
error is thrown instead of triggering the `fatalError` in
`KafkaProducerCloseOnTerminate`.
> `KafkaProducer.makeProducerWithEvents()` avoid `fatalError`

- Sources/Kafka/KafkaConsumer.swift
- Tests/IntegrationTests/KafkaTests.swift
This PR addresses issue #119.
The `KafkaConsumer` should not `fatalError` when storing offsets in
state `.finishing`.
See https://github.com/swift-server/swift-kafka-client/issues/119#issuecomment-1689660032 for more information why.
* terminate `KafkaConsumerMessages` sequences when in state `.finishing`
or `.finished` instead of storing offsets
> `KafkaConsumer`: store offsets when `.finishing`

- Sources/Kafka/RDKafka/RDKafkaClient.swift
Previously, we failed the entire `KafkaConsumer` if storing
a message offset through `RDKafkaClient.storeMessageOffset`
failed because the partition the offset should be committed to
was unassigned (which can happen during rebalance).
We should not fail the consumer when committing during
rebalance.
The worst thing that could happen here is that storing the offset
fails and we re-read a message, which is fine since KafkaConsumers with
automatic commits are designed for at-least-once processing:
https://docs.confluent.io/platform/current/clients/consumer.html#offset-management
* `RDKafkaClient.storeMessageOffset`: don't throw when receiving
error
`RD_KAFKA_RESP_ERR__STATE`
> `storeMessageOffset`: ignore state error

- Sources/Kafka/KafkaConsumer.swift
We should start assignments / subscriptions when `KafkaConsumer.run()`
is invoked and not on initialization.
* `KafkaConsumer`: move `assign` / `subscribe` from `init` to `func run()`
> Consumer: `assign` / `subscribe` on `run()`

- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/RDKafka/RDKafkaClient.swift
- Tests/IntegrationTests/KafkaTests.swift
Having `KafkaConsumer.commitSync` be `async` is not always convenient as
it suspends the `KafkaConsumer.messages` read loop and can therefore
lower throughput.
This PR introduces a new method `KafkaConsumer.commitAsync` that allows
users who don't care about the result of the `commit` to commit in a
"fire-and-forget" manner.
* new method `KafkaConsumer.commitAsync`
* rename `KafkaConsumer.StateMachine.commitSync` to
`KafkaConsumer.StateMachine.commit` to serve both `commitSync` and
`commitAsync`
* add new test for `KafkaConsumer.commitAsync`
> `KafkaConsumer.commitAsync`

- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/KafkaProducer.swift
Related to https://github.com/swift-server/swift-kafka-client/issues/125
ServiceLifecycle is not always required by end user, though `KafkaConsumer` and `KafkaProducer` can run without it.
However, it is impossible (in good manner) stop either of them without public method `triggerGracefulShutdown()`.
This PR allows makes `triggerGracefulShutdown()` public thus allow to use `KafkaConsumer`/`KafkaProducer` directly.
> Make triggerGracefulShutdown() public

- docker/docker-compose.2204.510.yaml
Motivation:
Now that Swift 5.9 is GM we should update the CI pipelines
Modifications:
* Add a 5.10 nightly docker compose file
* Update the 5.9 compose file to stop using nightlies
Result:
Remove add CI support for 5.10
> Add CI pipeline for Swift 5.10

- Package.swift
- Sources/Crdkafka/custom/include/openssl/err.h
- Sources/Crdkafka/custom/include/openssl/evp.h
- Sources/Crdkafka/custom/include/openssl/hmac.h
- Sources/Crdkafka/custom/include/openssl/pkcs12.h
- Sources/Crdkafka/custom/include/openssl/sha.h
- Sources/Crdkafka/custom/include/openssl/ssl.h
- Sources/Crdkafka/custom/include/openssl/x509.h
- Sources/Crdkafka/custom/include/openssl/x509_vfy.h
- docker/Dockerfile
Closes #123 
No need to install `libressl` on machine to build project.
* add dependency to `swift-nio-ssl` to obtain copy of `BoringSSL`
* create bridging headers allowing `librdkafka` to build with `BoringSSL` copy from `swift-nio-ssl`
* use `swift-service-lifecycle` version `2.1.0` instead of `beta`
> Ship with BoringSSL

- Sources/Kafka/RDKafka/RDKafkaClient.swift
**Motivation**
#129 attempted to ignore `RD_KAFKA_RESP_ERR_NO_ERROR` when executing `storeMessageOffset` func. However, the if test is inverted, it instead ignores all errors but `RD_KAFKA_RESP_ERR_NO_ERROR`. This PR fixes this.
**Modification**
* Fix `storeMessageOffset` error handling, ignore `RD_KAFKA_RESP_ERR_NO_ERROR`, stop ignoring other errors.
> Fix error test when ignoring RD_KAFKA_RESP_ERR_NO_ERROR in storeMessageOffset

- Sources/Kafka/Configuration/KafkaConsumerConfiguration.swift
- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/KafkaConsumerEvent.swift
- Sources/Kafka/KafkaProducer.swift
- Sources/Kafka/KafkaProducerEvent.swift
- Sources/Kafka/RDKafka/RDKafkaClient.swift
- Tests/IntegrationTests/KafkaTests.swift
Closes #131.
I ran an example consumer reading a topic with approx. `11_000_000` messages:
```swift
var consumerConfig = KafkaConsumerConfiguration(
consumptionStrategy: .partition(
KafkaPartition(rawValue: 0),
topic: "test-topic",
offset: KafkaOffset(rawValue: 0) // Important: Read from beginning!
),
bootstrapBrokerAddresses: [self.bootstrapBrokerAddress]
)
consumerConfig.pollInterval = .zero
consumerConfig.autoOffsetReset = .beginning // Always read topics from beginning
consumerConfig.broker.addressFamily = .v4
let consumer = try KafkaConsumer(
configuration: consumerConfig,
logger: .kafkaTest
)
let serviceGroupConfiguration = ServiceGroupConfiguration(services: [consumer], logger: .kafkaTest)
let serviceGroup = ServiceGroup(configuration: serviceGroupConfiguration)
try await …
```
> `KafkaConsumer`: back pressure  + improved read speed

- Sources/Crdkafka/custom/include/openssl/ssl.h
>Would appreciate a PR for it. I think the solution should be as easy as doing something like this `#define RAND_priv_bytes(x,sz) RAND_bytes((x),(sz))` in a C file where we shim boringssl to openssl.
_Originally posted by @FranzBusch in https://github.com/swift-server/swift-kafka-client/issues/138#issuecomment-1822864000_
As discussed. Let me know if there's a better place for the `#define`.
> Update to latest librdkafka & add a define for RAND_priv_bytes (#138)

- Sources/Kafka/KafkaConsumer.swift
Address #151. Exit from loop when no messages left.
> exit from consumer batch loop when no more messages left

- Sources/Kafka/KafkaConsumer.swift
- Tests/KafkaTests/KafkaConsumerTests.swift
- Tests/KafkaTests/KafkaProducerTests.swift
Addresses #147 
1. Lower requirements for `KafkaConsumer` state machine to avoid fatal error. + Add corresponding tests.
2. Add twin tests for `KafkaProducer` as a sanity check
> Lower requirements for consumer state machine

- Sources/Kafka/KafkaProducer.swift
Flush may throw exception thus source will not be finished.
Exception can be e.g. timeout (due to network outage): 
```
Caught exception KafkaError.rdKafkaError: Local: Timed out Kafka/RDKafkaClient.swift...
```
> Defer source.finish()

- Sources/Kafka/RDKafka/RDKafkaClient.swift
Sometimes it is possible to receive the following error:
```
KafkaError.rdKafkaError: Success
```
The problem is that last error is returned instead of resulting error from method.
> Use returned error

- Sources/Kafka/RDKafka/RDKafkaClient.swift
- Sources/Kafka/RDKafka/RDKafkaTopicHandles.swift
- Sources/Kafka/Utilities/SendableOpaquePointer.swift
[Unsafe pointers are no longer `Sendable`](https://github.com/swiftlang/swift/issues/70396#issuecomment-1851497237) starting with Swift 5.10, while a warning in earlier versions. This PR introduces `SendableOpaquePointer` to wrap `OpaquePointer` and marks it as `@unchecked Sendable`.
Resolves https://github.com/swift-server/swift-kafka-client/issues/159
> Introduce `SendableOpaquePointer`

- Sources/Kafka/KafkaAcknowledgedMessage.swift
- Sources/Kafka/KafkaConsumerMessage.swift
- Sources/Kafka/RDKafka/RDKafkaClient.swift
- Tests/KafkaTests/KafkaProducerTests.swift
When a message is being sent to Kafka the acknowledgement should also contains the headers.
Resolves https://github.com/swift-server/swift-kafka-client/issues/144
Reused the parsing function from KafkaConsumer in the producer path to return headers in the ack.
Headers available in the acknowledgement for producers and still available for consumers as well.
> Add headers to `KafkaAcknowledgedMessage`

- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/RDKafka/RDKafkaClient.swift
- Sources/Kafka/Utilities/DispatchQueueTaskExecutor.swift
- Sources/Kafka/Utilities/NaiveQueueExecutor.swift
We currently sleep for `pollInterval` when no new messages have been polled from the cluster. This leads to unnecessary slowness of the client. Instead of doing that, we now break up the polling of messages into two distinct approaches:
1. Attempt to poll synchronously: if there a message is polled, we return it. If there is no message, we immediately go to step 2.
2. We create a `DispatchQueue` and run the `consumerPoll` on it using `withTaskExecutorPreference`. We make the `consumerPoll` call wait for up to `pollInterval` before bailing.
This prevents us from sleeping on the running thread, and frees up cycles to do other work if required.
Resolves https://github.com/swift-server/swift-kafka-client/issues/165
> Poll for messages using `TaskExecutor`

- Package.swift
- Tests/IntegrationTests/KafkaTests.swift
Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.
> Enable MemberImportVisibility check on all targets

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/unit_tests.yml
- Sources/Kafka/Configuration/KafkaConfiguration+Security.swift
- Sources/Kafka/Configuration/KafkaConsumerConfiguration.swift
- Sources/Kafka/Configuration/KafkaProducerConfiguration.swift
- Sources/Kafka/Configuration/KafkaTopicConfiguration.swift
- Sources/Kafka/KafkaConsumer.swift
- Sources/Kafka/KafkaProducer.swift
CI use 6.1 nightlies, enable more soundness checks now that we can specify a pre-build command to set up the dependencies.
> CI use 6.1 nightlies, enable more soundness

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/unit_tests.yml
Motivation:
Swift 6.1 has been released, we should add it to our CI coverage.
Modifications:
Add additional Swift 6.1 jobs where appropriate in main.yml, pull_request.yml
Result:
Improved test coverage.
> Enable Swift 6.1 jobs in CI

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/unit_tests.yml
- Benchmarks/Package.swift
- Package.swift
Motivation:
Swift 5.9 is no longer supported, we should bump the tools version and remove it from our CI.
Modifications:
* Bump the Swift tools version to Swift 5.10
* Remove Swift 5.9 jobs where appropriate in main.yml, pull_request.yml
Result:
Code reflects our support window.
> Drop Swift 5.9

- Sources/Kafka/Configuration/KafkaConsumerConfiguration.swift
Motivation:
Currently the API doesn't provide a way to set the `fetch.wait.max.ms` Kafka consumer config. This PR enables the user to set it.
Modifications:
Added support for `fetch.wait.max.ms` inside of `KafkaConsumerConfiguration`.
Result:
We can set `fetch.wait.max.msa`.
> Add support for `fetch.wait.max.ms` Kafka consumer config
